name: Unlimited Auto Sync

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

# 🛡️ YEH NAYA RULE HAI (Double run block karne ke liye)
concurrency:
  group: sync-sheet-group
  cancel-in-progress: true

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Run Python Script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          MASTER_SHEET_ID: ${{ secrets.MASTER_SHEET_ID }}
        run: python main.py
